kind: Service
apiVersion: v1
metadata:
  name: prom-remotewrite
  namespace: openshift-monitoring  
spec: 
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: prom-remotewrite
