kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: prom-remotewrite
  namespace: openshift-monitoring 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom-remotewrite
  template:
    metadata:      
      labels:
        app: prom-remotewrite
    spec:
      volumes:
        - name: rewrite-certificate
          secret:
            secretName: rewrite-certificate
            defaultMode: 420
      containers:
        - resources: {}
          readinessProbe:
            httpGet:
              path: /ready
              port: rw-port
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: prom-remotewrite
          livenessProbe:
            httpGet:
              path: /health
              port: rw-port
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: INGESTION_URL
              value: ''
            - name: LISTENING_PORT
              value: '8081'
            - name: IDENTITY_TYPE
              value: aadApplication
            - name: AZURE_CLIENT_ID
              value: ''
            - name: AZURE_TENANT_ID
              value: ''
            - name: CLUSTER
              value: ARO-DOMAIN
            - name: AZURE_CLIENT_CERTIFICATE_PATH
              value: /mnt/secrets-store/metrics-certificate
          ports:
            - name: rw-port
              containerPort: 8081
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: rewrite-certificate
              readOnly: true
              mountPath: /mnt/secrets-store/
          terminationMessagePolicy: File
          image: >-
            mcr.microsoft.com/azuremonitor/prometheus/promdev/prom-remotewrite:prom-remotewrite-20221103.1
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  serviceName: prom-remotewrite
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10
